# Default, Defaults
markdown: #redcarpet --REMOVED ON DOWNLOAD BECAUSE OF EMAIL I RECIEVED ABOUT MARKDOWN NOT SUPPORTED ON GITHUB
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]

# Jekyll Defaults
title: Ladelle in Computer Science
email: ladelle.augustine@gmail.com
description: A small and simple site I made to test out Jekyll. Watch out! I'm going to make a material design theme next!
baseurl: "http://localhost:3000" # the subpath of your site, e.g. /blog

# Where can people find your site?
url: "http://localhost:3000"
# When developing, set this ^ equal to whatever localhost you're using

# Socail Media links
# Use these to link users to your organization's social media sites
twitter: N/A
facebook: N/A
google:  N/A

author: Ladelle Augustine
authorBio: From Psychology B.A to Computer science Masters student. 